### ISSUE TITLE
@typescript-eslint/naming-convention を緩くする

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/vite-react-ts-starter#5]
現状、camelCaseしか認めていない設定になっているため、APIの型を定義するときにfoo_barのような形式を作る際に不都合が生じている。そのためにルールを緩くする。
他の人のselectorとformatを参考にして追加修正を加えること

```yml
- selector: # PascalCaseなので、interfaceなんかも入れるべきかな？
    - typeAlias
    - typeParameter # TやUのこと？（実際にいじって調べる）
  format:
    - PascalCase
- selector:
    - property # これは特段camelCaseだけとは限らないため、削除
    - method
  format:
    - camelCase
```
